### ISSUE TITLE
Default bucket name is an invalid bucket name

### ISSUE THREAD

**Issue by slimandslam** [AWSTrainers/SysOps#1]
Error in Oregon region......

Cloudformation error:  CREATE_FAILED	AWS::S3::Bucket	ArtifactS3Bucket	Bucket name should not contain uppercase characters

Default bucket name should be a valid bucket name

**Comment by kbiton** [comment]
hey j , ArtifactS3Bucket is the default bucket name value of the parameter the user should replace it with a his own valid bucket name I will however change the default value to lower case...

Hopefully I understood your error report 

Kobi

**Comment by kbiton** [comment]
Fixed!  , default s3 bucket name is now lowercase
